import { SchemaTable } from './settings.models';

export const schemaTables: SchemaTable[] = [
  {
    tableName: 'dbo.sms_category',
    hebrewName: 'קטגוריות תבניות',
    purpose: 'מילון הקטגוריות העסקיות והקליניות שאליהן משויכות תבניות המסרון.',
    keys: ['PK: category_id'],
    columns: [
      'category_id',
      'category_name',
      'category_type',
      'is_active',
      'is_editable',
      'create_date',
      'update_date',
    ],
  },
  {
    tableName: 'dbo.sms_hospital',
    hebrewName: 'בתי חולים',
    purpose: 'מילון בתי החולים והמוסדות, כולל סוג המוסד, תיאור, שם וסטטוס פעילות.',
    keys: ['PK: hospital_id'],
    columns: [
      'hospital_type_id',
      'hospital_description',
      'hospital_id',
      'hospital_name',
      'is_active',
      'create_date',
      'update_date',
    ],
  },
  {
    tableName: 'dbo.sms_placeholder_catalog',
    hebrewName: 'קטלוג שדות דינמיים',
    purpose: 'מילון המשתנים שניתן לשלב בנוסח מסרון, כולל מקור הערך, ערך ברירת מחדל ומאפייני חובה ועריכה.',
    keys: ['PK: placeholder_id'],
    columns: [
      'placeholder_id',
      'placeholder_name',
      'display_name',
      'source_type',
      'value_source',
      'is_required',
      'is_static',
      'is_editable',
      'default_value',
      'create_date',
      'update_date',
    ],
  },
  {
    tableName: 'dbo.sms_reject_hospital_unit',
    hebrewName: 'החרגות בתי חולים ויחידות',
    purpose: 'רשימת בתי חולים ויחידות שבהם אין להפעיל או לשלוח תבנית מסרון מסוימת.',
    keys: [
      'PK מורכב: template_id + hospital_id + unit_id',
      'FK: hospital_id → dbo.sms_hospital.hospital_id',
    ],
    columns: ['template_id', 'hospital_id', 'unit_id', 'create_date', 'update_date'],
  },
  {
    tableName: 'dbo.sms_rules',
    hebrewName: 'כללי שליחת מסרונים',
    purpose: 'הגדרות התלות, חלונות הזמן, התוקף, המחזוריות ותנאי העצירה של כלל שליחה.',
    keys: ['לא מוגדר PK או FK במסד; rule_id היא עמודת IDENTITY'],
    columns: [
      'rule_id',
      'tt_id',
      'depend_on_tt_id',
      'dependency_max_minutes',
      'max_time_tokef_in_minutes',
      'is_constant',
      'is_recurring',
      'recurring_interval_days',
      'recurring_time_of_day',
      'recurring_stop_condition',
      'onetime_fallback_enabled',
      'onetime_fallback_time',
      'create_date',
      'update_date',
    ],
  },
  {
    tableName: 'dbo.sms_template',
    hebrewName: 'תבניות מסרון',
    purpose: 'פרטי הבסיס של תבנית מסרון: קוד, שם, קטגוריה, סטטוס פעילות, הרשאת עריכה ומספר גרסה.',
    keys: [
      'PK: template_id',
      'FK: category_id → dbo.sms_category.category_id',
    ],
    columns: [
      'template_id',
      'template_code',
      'template_name',
      'category_id',
      'is_active',
      'is_editable',
      'version_number',
      'create_date',
      'update_date',
    ],
  },
  {
    tableName: 'dbo.sms_template_language',
    hebrewName: 'נוסחי תבנית לפי שפה',
    purpose: 'נוסח המסרון לכל שפה של תבנית, כולל סימון שפת ברירת מחדל וסטטוס פעילות.',
    keys: ['PK: template_language_id'],
    columns: [
      'template_language_id',
      'template_id',
      'language_code',
      'template_text',
      'is_default',
      'is_active',
      'create_date',
      'update_date',
    ],
  },
  {
    tableName: 'dbo.sms_template_trigger',
    hebrewName: 'קישור תבניות לאירועים',
    purpose: 'קישור בין תבנית מסרון לבין אירוע מפעיל מתוך קטלוג הטריגרים.',
    keys: ['PK: tt_id'],
    columns: ['tt_id', 'trigger_id', 'template_id', 'create_date', 'update_date'],
  },
  {
    tableName: 'dbo.sms_trigger_catalog',
    hebrewName: 'קטלוג אירועים מפעילים',
    purpose: 'מילון האירועים שיכולים להפעיל תבניות מסרון, כולל קוד, שם, תיאור וסטטוס פעילות.',
    keys: ['PK: trigger_id'],
    columns: [
      'trigger_id',
      'trigger_code',
      'trigger_name',
      'description',
      'is_active',
      'create_date',
      'update_date',
    ],
  },
  {
    tableName: 'dbo.sms_unit',
    hebrewName: 'יחידות ומחלקות',
    purpose: 'מילון היחידות והמחלקות בכל בית חולים, כולל סוג היחידה וסטטוס הפעילות.',
    keys: ['PK מורכב: hospital_id + unit_id'],
    columns: [
      'hospital_id',
      'unit_id',
      'unit_type',
      'unit_name',
      'is_active',
      'create_date',
      'update_date',
    ],
  },
];
